[package]
name = "hello-strictrs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]

[dev-dependencies]
proptest = { version = "=1.11.0", default-features = false, features = ["std"] }

[lints.rust]
unsafe_code = "deny"
unused_must_use = "deny"

[lints.clippy]
as_conversions = "deny"
wildcard_imports = "deny"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
