use std::fs;
use std::path::{Path, PathBuf};

const CARGO_CONFIG: &str = r#"[alias]
release-small = "build --release --locked --target x86_64-unknown-linux-musl -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort"

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-Zlocation-detail=none",
    "-Zfmt-debug=none",
]
"#;

const GITIGNORE: &str = "/target\n";

const TOOLCHAIN: &str = r#"[toolchain]
channel = "nightly-2026-07-14"
components = ["clippy", "rust-src", "rustfmt"]
profile = "minimal"
targets = ["x86_64-unknown-linux-musl"]
"#;

pub fn create_project(parent: &Path, name: &str) -> Result<PathBuf, String> {
    validate_name(name)?;

    let destination = parent.join(name);
    if destination.exists() {
        return Err(format!("destination already exists: {}", destination.display()));
    }

    let staging = parent.join(format!(".{name}.strictrs-tmp"));
    if staging.exists() {
        return Err(format!("staging path already exists: {}", staging.display()));
    }

    fs::create_dir(&staging)
        .map_err(|error| format!("failed to create {}: {error}", staging.display()))?;

    let result = write_project(&staging, name);
    if let Err(error) = result {
        let _ = fs::remove_dir_all(&staging);
        return Err(error);
    }

    fs::rename(&staging, &destination).map_err(|error| {
        let _ = fs::remove_dir_all(&staging);
        format!(
            "failed to move {} to {}: {error}",
            staging.display(),
            destination.display()
        )
    })?;

    Ok(destination)
}

fn validate_name(name: &str) -> Result<(), String> {
    let mut characters = name.chars();
    let Some(first) = characters.next() else {
        return Err("project name cannot be empty".to_owned());
    };

    if !first.is_ascii_lowercase() {
        return Err("project name must start with a lowercase ASCII letter".to_owned());
    }

    if characters.any(|character| {
        !character.is_ascii_lowercase()
            && !character.is_ascii_digit()
            && character != '-'
            && character != '_'
    }) {
        return Err(
            "project name may contain only lowercase ASCII letters, digits, '-' and '_'".to_owned(),
        );
    }

    Ok(())
}

fn write_project(project: &Path, name: &str) -> Result<(), String> {
    fs::create_dir(project.join(".cargo"))
        .map_err(|error| format!("failed to create .cargo: {error}"))?;
    fs::create_dir(project.join("src"))
        .map_err(|error| format!("failed to create src: {error}"))?;

    write_file(project, ".cargo/config.toml", CARGO_CONFIG)?;
    write_file(project, ".gitignore", GITIGNORE)?;
    write_file(project, "Cargo.lock", &render_lockfile(name))?;
    write_file(project, "Cargo.toml", &render_manifest(name))?;
    write_file(project, "README.md", &render_readme(name))?;
    write_file(project, "rust-toolchain.toml", TOOLCHAIN)?;
    write_file(project, "src/main.rs", &render_main(name))?;

    Ok(())
}

fn write_file(project: &Path, relative: &str, content: &str) -> Result<(), String> {
    let path = project.join(relative);
    fs::write(&path, content)
        .map_err(|error| format!("failed to write {}: {error}", path.display()))
}

fn render_manifest(name: &str) -> String {
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]

[lints.rust]
unsafe_code = "deny"
unused_must_use = "deny"

[lints.clippy]
as_conversions = "deny"
wildcard_imports = "deny"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
"#
    )
}

fn render_lockfile(name: &str) -> String {
    format!(
        r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "{name}"
version = "0.1.0"
"#
    )
}

fn render_main(name: &str) -> String {
    format!(
        r#"#![cfg_attr(
    not(test),
    deny(
        clippy::expect_used,
        clippy::indexing_slicing,
        clippy::unwrap_used
    )
)]

fn main() {{
    println!("Hello from {name}.");
}}
"#
    )
}

fn render_readme(name: &str) -> String {
    format!(
        r#"# {name}

Generated by `strictrs new`.

## Validate

```bash
cargo fmt --check
cargo clippy --all-targets --all-features --locked -- -D warnings
cargo test --locked
```

## Small static release

```bash
cargo release-small
```

The release alias uses the pinned nightly toolchain, rebuilds the standard library with immediate-abort panic support, targets `x86_64-unknown-linux-musl`, and uses the footprint profile in `Cargo.toml`.
"#
    )
}
