use std::fs;
use std::path::{Path, PathBuf};

const CARGO_CONFIG: &str = r#"[alias]
release-small = "build --release --locked --target x86_64-unknown-linux-musl"
"#;

const GITIGNORE: &str = "/target\n";
const LOCKFILE_TEMPLATE: &str = include_str!("../fixtures/m3-template/Cargo.lock");

const PROPERTIES: &str = r#"use proptest::collection::vec;
use proptest::prelude::{any, prop_assert_eq, proptest};

proptest! {
    #[test]
    fn reversing_twice_preserves_values(values in vec(any::<u8>(), 0..256)) {
        let mut transformed = values.clone();
        transformed.reverse();
        transformed.reverse();

        prop_assert_eq!(transformed, values);
    }
}
"#;

const TOOLCHAIN: &str = r#"[toolchain]
channel = "1.97.1"
components = ["clippy", "rustfmt"]
profile = "minimal"
targets = ["x86_64-unknown-linux-musl"]
"#;

pub fn create_project(parent: &Path, name: &str) -> Result<PathBuf, String> {
    validate_name(name)?;

    let destination = parent.join(name);
    if destination.exists() {
        return Err(format!(
            "destination already exists: {}",
            destination.display()
        ));
    }

    let staging = parent.join(format!(".{name}.strictrs-tmp"));
    if staging.exists() {
        return Err(format!(
            "staging path already exists: {}",
            staging.display()
        ));
    }

    fs::create_dir(&staging)
        .map_err(|error| format!("failed to create {}: {error}", staging.display()))?;

    let result = write_project(&staging, name);
    if let Err(error) = result {
        let _ = fs::remove_dir_all(&staging);
        return Err(error);
    }

    fs::rename(&staging, &destination).map_err(|error| {
        let _ = fs::remove_dir_all(&staging);
        format!(
            "failed to move {} to {}: {error}",
            staging.display(),
            destination.display()
        )
    })?;

    Ok(destination)
}

fn validate_name(name: &str) -> Result<(), String> {
    let mut characters = name.chars();
    let Some(first) = characters.next() else {
        return Err("project name cannot be empty".to_owned());
    };

    if !first.is_ascii_lowercase() {
        return Err("project name must start with a lowercase ASCII letter".to_owned());
    }

    if characters.any(|character| {
        !character.is_ascii_lowercase()
            && !character.is_ascii_digit()
            && character != '-'
            && character != '_'
    }) {
        return Err(
            "project name may contain only lowercase ASCII letters, digits, '-' and '_'".to_owned(),
        );
    }

    Ok(())
}

fn write_project(project: &Path, name: &str) -> Result<(), String> {
    fs::create_dir(project.join(".cargo"))
        .map_err(|error| format!("failed to create .cargo: {error}"))?;
    fs::create_dir(project.join("src"))
        .map_err(|error| format!("failed to create src: {error}"))?;
    fs::create_dir(project.join("tests"))
        .map_err(|error| format!("failed to create tests: {error}"))?;

    write_file(project, ".cargo/config.toml", CARGO_CONFIG)?;
    write_file(project, ".gitignore", GITIGNORE)?;
    write_file(project, "Cargo.lock", &render_lockfile(name))?;
    write_file(project, "Cargo.toml", &render_manifest(name))?;
    write_file(project, "README.md", &render_readme(name))?;
    write_file(project, "rust-toolchain.toml", TOOLCHAIN)?;
    write_file(project, "src/main.rs", &render_main(name))?;
    write_file(project, "tests/properties.rs", PROPERTIES)?;

    Ok(())
}

fn write_file(project: &Path, relative: &str, content: &str) -> Result<(), String> {
    let path = project.join(relative);
    fs::write(&path, content)
        .map_err(|error| format!("failed to write {}: {error}", path.display()))
}

fn render_manifest(name: &str) -> String {
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"
rust-version = "1.97.1"
publish = false

[dependencies]

[dev-dependencies]
proptest = {{ version = "=1.11.0", default-features = false, features = ["std"] }}

[lints.rust]
unsafe_code = "deny"
unused_must_use = "deny"

[lints.clippy]
as_conversions = "deny"
wildcard_imports = "deny"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
"#
    )
}

fn render_lockfile(name: &str) -> String {
    LOCKFILE_TEMPLATE.replacen(
        "name = \"hello-strictrs\"",
        &format!("name = \"{name}\""),
        1,
    )
}

fn render_main(name: &str) -> String {
    format!(
        r#"#![cfg_attr(
    not(test),
    deny(clippy::expect_used, clippy::indexing_slicing, clippy::unwrap_used)
)]

fn main() {{
    println!("Hello from {name}.");
}}
"#
    )
}

fn render_readme(name: &str) -> String {
    format!(
        r#"# {name}

Generated by `strictrs new` with Rust 1.97.1.

## Validate

```bash
cargo fmt --check
cargo clippy --all-targets --all-features --locked -- -D warnings
cargo test --locked
```

## Property tests

`tests/properties.rs` contains a starter invariant using the exact-pinned `proptest` dev dependency. Replace the sample property with domain invariants; generated inputs are reduced to a minimal failing case when a property breaks.

Run only the property suite with:

```bash
cargo test --locked --test properties
```

## Small static release

```bash
cargo release-small
```

The release alias uses the pinned Rust 1.97.1 stable toolchain, the prebuilt `x86_64-unknown-linux-musl` standard library, and the footprint profile in `Cargo.toml`.
"#
    )
}
